services:
  postgres:
    image: postgres:18-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bird_api
    volumes:
      - db:/var/lib/postgresql

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  db: